package com.buyalskaya.appliance.service.validation;

public class ExtremumValueSearchCriteria {
    final static int MIN_POWER_CONSUMPTION = 1;
    final static int MAX_POWER_CONSUMPTION = 5000;
    final static double MIN_BATTERY_CAPACITY = 0.5;
    final static double MAX_BATTERY_CAPACITY = 10;
    final static double MIN_WEIGHT = 0.5;
    final static double MAX_WEIGHT = 50;
    final static int MIN_DISPLAY_INCHES = 5;
    final static int MAX_DISPLAY_INCHES = 50;
    final static int MIN_NUMBER_OF_SPEAKERS = 1;
    final static int MAX_NUMBER_OF_SPEAKERS = 6;
    final static double MIN_CAPACITY = 10;
    final static double MAX_CAPACITY = 100;
    final static int MIN_MEMORY_ROM = 100;
    final static int MAX_MEMORY_ROM = 100000;
    final static double MIN_FREEZER_CAPACITY = 1;
    final static double MAX_FREEZER_CAPACITY = 100;
    final static double MIN_FREQUENCY = 1;
    final static double MAX_FREQUENCY = 100;
    final static double MIN_DEPTH = 1;
    final static double MAX_DEPTH = 1000;
    final static int MIN_SYSTEM_MEMORY = 100;
    final static int MAX_SYSTEM_MEMORY = 100000;
    final static double MIN_OVERALL_CAPACITY = 100;
    final static double MAX_OVERALL_CAPACITY = 1000;
    final static int MIN_FLASH_MEMORY_CAPACITY = 1;
    final static int MAX_FLASH_MEMORY_CAPACITY = 10;
    final static double MIN_CORD_LENGTH = 1;
    final static double MAX_CORD_LENGTH = 10;
    final static double MIN_HEIGHT = 1;
    final static double MAX_HEIGHT = 100;
    final static double MIN_CPU = 0.5;
    final static double MAX_CPU = 5;
    final static double MIN_MOTOR_SPEED_REGULATION =1000;
    final static double MAX_MOTOR_SPEED_REGULATION = 10000;
    final static double MIN_WIDTH = 1;
    final static double MAX_WIDTH = 100;
    final static double MIN_CLEANING_WIDTH= 1;
    final static double MAX_CLEANING_WIDTH = 100;
}
